CREATE TABLE [dbo].[Chetak_VIN_Battery_Data_Stg_1]
(
	[VIN] [nvarchar](max) NULL,
	[Vehicle SKU] [nvarchar](max) NULL,
	[Veh SKU (ZZ)] [nvarchar](max) NULL,
	[SKU Description] [nvarchar](max) NULL,
	[Brand] [nvarchar](max) NULL,
	[Veh Production Date] [date] NULL,
	[Vehicle Dispatch Date] [date] NULL,
	[Sold to] [nvarchar](max) NULL,
	[DEALERNAME] [nvarchar](max) NULL,
	[CITY] [nvarchar](max) NULL,
	[DISTRICT] [nvarchar](max) NULL,
	[STATE1] [nvarchar](max) NULL,
	[CIRCLE] [nvarchar](max) NULL,
	[Latest battery replace Date] [nvarchar](max) NULL,
	[Latest Battery ] [nvarchar](max) NULL,
	[Flag] [nvarchar](max) NULL,
	[Replaced Count] [nvarchar](max) NULL,
	[Replaced Batteries] [nvarchar](max) NULL,
	[BIN CC] [nvarchar](max) NULL,
	[BIN Capacity] [nvarchar](max) NULL,
	[BIN BMS Supplier] [nvarchar](max) NULL,
	[BIN BMS Mfgr] [nvarchar](max) NULL,
	[BIN Cell part no] [nvarchar](max) NULL,
	[BIN Battery Config] [nvarchar](max) NULL,
	[BIN Pack Supplier] [nvarchar](max) NULL,
	[BINARY Data] [nvarchar](max) NULL,
	[BIN Mfg Date] [nvarchar](max) NULL,
	[BIN Assly Line] [nvarchar](max) NULL,
	[BIN Rev] [nvarchar](max) NULL,
	[Latest BIN Rev] [nvarchar](max) NULL,
	[Org BIN Age when Replaced] [nvarchar](max) NULL,
	[JC Date Org BIN Replaced] [nvarchar](max) NULL,
	[KMS Org BIN Replaced] [nvarchar](max) NULL,
	[JC Date Latest BIN Replaced] [nvarchar](max) NULL,
	[KMS L BIN Fitted] [nvarchar](max) NULL,
	[Charge Cycles Org BIN] [nvarchar](max) NULL,
	[Corrected BAL BIN] [nvarchar](max) NULL,
	[Mfg BIN (Chassis Master)] [nvarchar](max) NULL,
	[Combine Barcode] [nvarchar](max) NULL,
	[EOL Date (Exittime)] [nvarchar](max) NULL,
	[Cell supplier] [nvarchar](max) NULL,
	[Org] [nvarchar](max) NULL,
	[Corrected] [nvarchar](max) NULL,
	[CHASSIS_NO] [nvarchar](max) NULL,
	[ALERT_DATE] [nvarchar](max) NULL,
	[ALERT_TIME] [nvarchar](max) NULL,
	[SEVERITY] [nvarchar](max) NULL,
	[WERKS] [nvarchar](max) NULL,
	[CUST_COMPL] [nvarchar](max) NULL,
	[BARND_NAME] [nvarchar](max) NULL,
	[CUST_V_DESC] [nvarchar](max) NULL,
	[DEFECT_CODE] [nvarchar](max) NULL,
	[REASON] [nvarchar](max) NULL,
	[PRODUCTIONMONTH] [nvarchar](max) NULL,
	[PART_NO] [nvarchar](max) NULL,
	[PART_NAME] [nvarchar](max) NULL,
	[KMS] [nvarchar](max) NULL,
	[VEND_CATG] [nvarchar](max) NULL,
	[LIFNR] [nvarchar](max) NULL,
	[NAME1] [nvarchar](max) NULL,
	[PHY_PHENO] [nvarchar](max) NULL,
	[CRT_ACTN] [nvarchar](max) NULL,
	[ACTN_BRF] [nvarchar](max) NULL,
	[CUST_V_CODE] [nvarchar](max) NULL,
	[DEF_DESC] [nvarchar](max) NULL,
	[BATTERY_FAILURE_CLASSIFICATION] [varchar](3) NULL
)